    --Insert 
    INSERT INTO T_MC_CARTAO_CREDITO_CLI (ID_CARTAO_CREDITO, NR_CARTAO_CREDITO, NM_CLIENTE_CARTAO, NM_BANDEIRA_CARTAO, MES_ANO_VENCTO, NR_CODIGO_SEGURANCA) 
    VALUES (1, 1111222233334444, 'Adrielle Gennaro', 'VISA', 122028, 123);

    INSERT INTO T_MC_CARTAO_CREDITO_CLI (ID_CARTAO_CREDITO, NR_CARTAO_CREDITO, NM_CLIENTE_CARTAO, NM_BANDEIRA_CARTAO, MES_ANO_VENCTO, NR_CODIGO_SEGURANCA) 
    VALUES (2, 5555666677778888, 'Neemias Silva', 'MASTERCARD', 052027, 456);

    INSERT INTO T_MC_CARTAO_CREDITO_CLI (ID_CARTAO_CREDITO, NR_CARTAO_CREDITO, NM_CLIENTE_CARTAO, NM_BANDEIRA_CARTAO, MES_ANO_VENCTO, NR_CODIGO_SEGURANCA) 
    VALUES (3, 9999000011112222, 'Paulo Santos', 'AMEX', 102029, 789);

    --UPDATES
    UPDATE T_MC_CARTAO_CREDITO_CLI SET NM_BANDEIRA_CARTAO = 'MASTERCARD' WHERE ID_CARTAO_CREDITO = 1;
    UPDATE T_MC_CARTAO_CREDITO_CLI SET MES_ANO_VENCTO = 122030 WHERE ID_CARTAO_CREDITO = 2;
    UPDATE T_MC_CARTAO_CREDITO_CLI SET NR_CODIGO_SEGURANCA = 999 WHERE ID_CARTAO_CREDITO = 3;

    --DELETE
    DELETE FROM T_MC_CARTAO_CREDITO_CLI WHERE ID_CARTAO_CREDITO = 3;